[mongodb]
mongodb-dev.devopstest.fun

[catalogue]
catalogue-dev.devopstest.fun

[redis]
redis-dev.devopstest.fun

[user]
user-dev.devopstest.fun

[cart]
cart-dev.devopstest.fun

[mysql]
mysql-dev.devopstest.fun

[rabbitmq]
rabbitmq-dev.devopstest.fun

[shipping]
shipping-dev.devopstest.fun

[payment]
payment-dev.devopstest.fun

[frontend]
frontend-dev.devopstest.fun